tinyMCE.addI18n('en.images_dlg', {
    title: 'Upload and insert image',
    normal_upload: 'Normal upload',
    multi_upload: 'Multiupload',
    select_file: 'Select file',
    files_uploaded: 'Files uploaded',
    upload: 'Upload',
    select_few_files: 'Select few files',
    browse: 'Browse&#133;',
    cancel_all_uploads: 'Cancel all uploads',
    loading_content: 'SWFUpload is loading. Please wait a moment...',
    long_loading: 'SWFUpload is taking a long time to load or the load has failed.  Please make sure that the Flash Plugin is enabled and that a working version of the Adobe Flash Player is installed.',
    alternate_content: 'We\'re sorry.  SWFUpload could not load.  You may need to install or upgrade Flash Player. Visit the <a href="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash">Adobe website</a> to get the Flash Player.',
    insert_image: 'Insert image',
    create_dir: 'Create dir',
    remove_dir: 'Remove dir',
    cancel_creating: 'Cancel creating',
    cancel_dir_creating: 'Cancel dir creating',
    create: 'Create',
    confirm_dir_creating: 'Confirm dir creating',
    upload_files: 'Upload files',
    delete_files: 'Delete files',
    loading: 'Loading',
    save: 'Save',
    edit: 'Edit',
    upload_date: 'Upload date',
    image_size: 'Image size',
    files: 'Files',
    link_to_file: 'Link to file',
    link_: 'Link',
    size: 'Size',
    images: 'Images',
    files: 'Files',
    enter_a_name_for_new_folder: 'Enter a name for new folder',
    delete_folder: 'Delete folder',
    select_files_to_delete: 'Select files to delete.\n\nYou can select multiple files at once, so hold Ctrl while selecting.',
    delete_file: 'Delete file',
    files_to_delete: 'Files to delete',
    continue_: 'Continue',
    files_selected: 'Files selected',
    files_total: 'Files',
    bytes: 'b',
    kbytes: 'kb',
    mbytes: 'Mb',
    remove: 'Remove',
    you_can_not_upload: 'You can not upload files with the extension $ext!',
    file_already_added: 'File $file already added',
    all_files: 'All files'
});
